services:
  - type: web
    name: dondesang-backend
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dondesang-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: JWT_SECRET
        sync: false
      - key: DEV_LOG_TOKEN
        sync: false
      - key: DEV_LOG_EMAIL
        sync: false
      - key: DEV_LOG_PASSWORD
        sync: false
      - key: DEFAULT_ADMIN_EMAIL
        sync: false
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
      - key: DEFAULT_DANTEC_EMAIL
        sync: false
      - key: DEFAULT_DANTEC_PASSWORD
        sync: false
      - key: DEFAULT_FANN_EMAIL
        sync: false
      - key: DEFAULT_FANN_PASSWORD
        sync: false

databases:
  - name: dondesang-db
    region: oregon
    databaseName: dondesang
    user: dondesang_user
