export type BloodType = "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-";

export interface CenterDirectoryEntry {
  key: string;
  email: string;
  password: string;
  hospitalName: string;
  city: string;
  address: string;
  phone: string;
  openingHours: string;
  coordinates: string;
  defaultDistance: string;
  supportedBloodTypes: BloodType[];
}

export const ALL_BLOOD_TYPES: BloodType[] = [
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
];

export const CENTER_DIRECTORY: CenterDirectoryEntry[] = [
  {
    key: "cnts",
    email: "cnts@dondesang.sn",
    password: "Cnts@2026",
    hospitalName: "Centre National de Transfusion Sanguine (CNTS)",
    city: "Dakar",
    address: "Avenue Cheikh Anta Diop, Fann Résidence",
    phone: "+221 33 825 92 92",
    openingHours: "Lun-Ven: 8h-17h, Sam: 8h-13h",
    coordinates: "14.7167,-17.4677",
    defaultDistance: "2.5 km",
    supportedBloodTypes: ALL_BLOOD_TYPES,
  },
  {
    key: "dantec",
    email: "dantec@dondesang.sn",
    password: "Dantec@2026",
    hospitalName: "Hôpital Le Dantec",
    city: "Dakar",
    address: "Avenue Pasteur, Dakar",
    phone: "+221 33 839 50 50",
    openingHours: "Lun-Dim: 24h/24",
    coordinates: "14.6936,-17.4439",
    defaultDistance: "3.8 km",
    supportedBloodTypes: ALL_BLOOD_TYPES,
  },
  {
    key: "fann",
    email: "fann@dondesang.sn",
    password: "Fann@2026",
    hospitalName: "Hôpital Fann",
    city: "Dakar",
    address: "Fann Résidence, Dakar",
    phone: "+221 33 869 18 18",
    openingHours: "Lun-Dim: 24h/24",
    coordinates: "14.6932,-17.4671",
    defaultDistance: "4.1 km",
    supportedBloodTypes: ALL_BLOOD_TYPES,
  },
  {
    key: "hopital-regional-dakar",
    email: "hrdakar@dondesang.sn",
    password: "Hrdakar@2026",
    hospitalName: "Hôpital Régional de Dakar",
    city: "Dakar",
    address: "Avenue Blaise Diagne, Dakar Plateau",
    phone: "+221 33 821 21 81",
    openingHours: "Lun-Dim: 24h/24",
    coordinates: "14.7167,-17.4677",
    defaultDistance: "3.2 km",
    supportedBloodTypes: ["A+", "A-", "B+", "O+", "O-"],
  },
  {
    key: "hopital-regional-thies",
    email: "hrthies@dondesang.sn",
    password: "Hrthies@2026",
    hospitalName: "Hôpital Régional de Thiès",
    city: "Thiès",
    address: "Avenue Lamine Gueye, Thiès",
    phone: "+221 33 951 10 18",
    openingHours: "Lun-Dim: 24h/24",
    coordinates: "14.7886,-16.9260",
    defaultDistance: "70 km",
    supportedBloodTypes: ["A+", "B+", "O+", "AB+", "O-"],
  },
  {
    key: "hopital-regional-saint-louis",
    email: "hrsaintlouis@dondesang.sn",
    password: "Hrsaintlouis@2026",
    hospitalName: "Hôpital Régional de Saint-Louis",
    city: "Saint-Louis",
    address: "Avenue Général de Gaulle, Saint-Louis",
    phone: "+221 33 961 11 95",
    openingHours: "Lun-Ven: 8h-17h, Sam: 8h-13h",
    coordinates: "16.0179,-16.4897",
    defaultDistance: "265 km",
    supportedBloodTypes: ["A+", "B+", "O+", "AB+"],
  },
  {
    key: "hopital-regional-kaolack",
    email: "hrkaolack@dondesang.sn",
    password: "Hrkaolack@2026",
    hospitalName: "Hôpital Régional de Kaolack",
    city: "Kaolack",
    address: "Quartier Médina, Kaolack",
    phone: "+221 33 941 10 74",
    openingHours: "Lun-Ven: 8h-18h",
    coordinates: "14.1500,-16.0767",
    defaultDistance: "192 km",
    supportedBloodTypes: ["A+", "B+", "O+", "O-"],
  },
  {
    key: "hopital-regional-ziguinchor",
    email: "hrziguinchor@dondesang.sn",
    password: "Hrziguinchor@2026",
    hospitalName: "Hôpital Régional de Ziguinchor",
    city: "Ziguinchor",
    address: "Quartier Kandé, Ziguinchor",
    phone: "+221 33 991 11 72",
    openingHours: "Lun-Dim: 24h/24",
    coordinates: "12.5833,-16.2667",
    defaultDistance: "450 km",
    supportedBloodTypes: ["A+", "B+", "O+", "AB+"],
  },
  {
    key: "hopital-regional-diourbel",
    email: "hrdiourbel@dondesang.sn",
    password: "Hrdiourbel@2026",
    hospitalName: "Hôpital Régional de Diourbel",
    city: "Diourbel",
    address: "Route de Bambey, Diourbel",
    phone: "+221 33 971 10 58",
    openingHours: "Lun-Ven: 8h-17h",
    coordinates: "14.6500,-16.2333",
    defaultDistance: "150 km",
    supportedBloodTypes: ["A+", "B+", "O+"],
  },
  {
    key: "hopital-regional-louga",
    email: "hrlouga@dondesang.sn",
    password: "Hrlouga@2026",
    hospitalName: "Hôpital Régional de Louga",
    city: "Louga",
    address: "Avenue Abdoulaye Wade, Louga",
    phone: "+221 33 967 10 25",
    openingHours: "Lun-Ven: 8h-18h",
    coordinates: "15.6167,-16.2167",
    defaultDistance: "205 km",
    supportedBloodTypes: ["A+", "B+", "O+", "O-"],
  },
  {
    key: "hopital-regional-tambacounda",
    email: "hrtamba@dondesang.sn",
    password: "Hrtamba@2026",
    hospitalName: "Hôpital Régional de Tambacounda",
    city: "Tambacounda",
    address: "Quartier Gourel Diadji, Tambacounda",
    phone: "+221 33 981 11 44",
    openingHours: "Lun-Dim: 24h/24",
    coordinates: "13.7667,-13.6667",
    defaultDistance: "430 km",
    supportedBloodTypes: ["A+", "B+", "O+", "AB+"],
  },
  {
    key: "hopital-regional-kolda",
    email: "hrkolda@dondesang.sn",
    password: "Hrkolda@2026",
    hospitalName: "Hôpital Régional de Kolda",
    city: "Kolda",
    address: "Quartier Saré Kémo, Kolda",
    phone: "+221 33 996 11 38",
    openingHours: "Lun-Ven: 8h-17h",
    coordinates: "12.8833,-14.9500",
    defaultDistance: "620 km",
    supportedBloodTypes: ["A+", "B+", "O+"],
  },
  {
    key: "hopital-regional-matam",
    email: "hrmatam@dondesang.sn",
    password: "Hrmatam@2026",
    hospitalName: "Hôpital Régional de Matam",
    city: "Matam",
    address: "Quartier Escale, Matam",
    phone: "+221 33 966 61 23",
    openingHours: "Lun-Ven: 8h-18h",
    coordinates: "15.6556,-13.2553",
    defaultDistance: "450 km",
    supportedBloodTypes: ["A+", "B+", "O+", "O-"],
  },
  {
    key: "hopital-regional-fatick",
    email: "hrfatick@dondesang.sn",
    password: "Hrfatick@2026",
    hospitalName: "Hôpital Régional de Fatick",
    city: "Fatick",
    address: "Route de Kaolack, Fatick",
    phone: "+221 33 949 11 56",
    openingHours: "Lun-Ven: 8h-17h",
    coordinates: "14.3333,-16.4167",
    defaultDistance: "165 km",
    supportedBloodTypes: ["A+", "B+", "O+"],
  },
  {
    key: "hopital-regional-kaffrine",
    email: "hrkaffrine@dondesang.sn",
    password: "Hrkaffrine@2026",
    hospitalName: "Hôpital Régional de Kaffrine",
    city: "Kaffrine",
    address: "Quartier Médina Baye, Kaffrine",
    phone: "+221 33 945 10 89",
    openingHours: "Lun-Ven: 8h-18h",
    coordinates: "14.1067,-15.5500",
    defaultDistance: "280 km",
    supportedBloodTypes: ["A+", "B+", "O+", "AB+"],
  },
  {
    key: "hopital-regional-kedougou",
    email: "hrkedougou@dondesang.sn",
    password: "Hrkedougou@2026",
    hospitalName: "Hôpital Régional de Kédougou",
    city: "Kédougou",
    address: "Quartier Centre, Kédougou",
    phone: "+221 33 985 11 67",
    openingHours: "Lun-Dim: 24h/24",
    coordinates: "12.5500,-12.1833",
    defaultDistance: "720 km",
    supportedBloodTypes: ["A+", "B+", "O+"],
  },
  {
    key: "hopital-regional-sedhiou",
    email: "hrsedhiou@dondesang.sn",
    password: "Hrsedhiou@2026",
    hospitalName: "Hôpital Régional de Sédhiou",
    city: "Sédhiou",
    address: "Quartier Escale, Sédhiou",
    phone: "+221 33 995 11 42",
    openingHours: "Lun-Ven: 8h-17h",
    coordinates: "12.7083,-15.5567",
    defaultDistance: "550 km",
    supportedBloodTypes: ["A+", "B+", "O+", "O-"],
  },
];

export function normalizeText(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim()
    .toLowerCase();
}
